UInt8|16|32 as derived type instead of subtypes
AdaCore/svd2ada pull request #32
Opened 2017-02-13 20:24 UTC by Fabien-Chouteau

I also add two SVD files used in the Ada_Drivers_Library that where missing here.

2017-02-13 20:29 UTC, lambourg requested changes
Can you split changes for cortex-m0 and the ones for UIntx definitions? Those are unrelated so deserve separate reviews.

2017-02-13 20:41 UTC, simonjwright commented
Don’t see why Uint8|16|32 (and 64!) aren’t made `mod 2 ** x` for consistency, in line with the e0a308a change.

2017-02-13 20:44 UTC, pat-rogers commented
On 2/13/2017 2:41 PM, Simon Wright wrote:
> Don’t see why Uint8|16|32 (and 64!) aren’t made `mod 2 ** x` for consistency, in line with the e0a308a change.


Because then we won't get the shift/rotate functions.

2017-02-13 20:53 UTC, simonjwright commented
On 13 Feb 2017, at 20:44, Pat Rogers <notifications@github.com> wrote:

> On 2/13/2017 2:41 PM, Simon Wright wrote:
> > Don’t see why Uint8|16|32 (and 64!) aren’t made `mod 2 ** x` for consistency, in line with the e0a308a change.
> 
> 
> Because then we won't get the shift/rotate functions.

That makes sense. (and my mentioning 64 was because it's missing from the commit title even though it's actually present in the commit)

2017-02-16 19:44 UTC, lambourg commented
After experiencing this change a bit, I find that:

1. Changing from a subtype to a derived type is easier for the user to handle, so agree with that
2. Renaming Byte to UInt8 is unnecessary, and leads to too much refactoring, while Byte is already very explicit (there's no occasion where this can be misleading).

What is the rationale that would lead to this Byte to UInt8 renaming being necessary (apart from pure aesthetic point of view)?

2017-02-17 17:34 UTC, Fabien-Chouteau commented
> Renaming Byte to UInt8 is unnecessary, and leads to too much refactoring,

Most of the refactoring is done. Refactoring the refactoring would lead to to much refactoring ;)

> while Byte is already very explicit (there's no occasion where this can be misleading).

Byte is more a size of data (8bit) than a type, it doesn't say if it's signed or not for instance. 
The type we define here is an unsigned integer of size 8: UInt8. Like we define UInt9 for an unsigned integer of size 9.

Since you are the only one against this change, I suggest you add an option to revert back to Byte if think it's important.

2017-02-17 17:37 UTC, merged